# Generated by Django 3.1 on 2020-08-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_organization_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyDonatorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=264)),
                ('email', models.CharField(blank=True, max_length=264)),
                ('contact', models.CharField(blank=True, max_length=264)),
                ('opinion', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
