# Generated by Django 3.1 on 2020-08-18 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_moneydonatorinfo_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='goal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='moneydonatorinfo',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.event'),
        ),
    ]
