# Generated by Django 3.1 on 2020-08-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200818_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
