# Generated by Django 3.1 on 2020-08-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_event_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('MY', 'Money'), ('BL', 'Belongings'), ('BH', 'Both')], default='MY', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.ImageField(default='f.jpg', null=True, upload_to=''),
        ),
    ]
