# Generated by Django 3.1 on 2020-08-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200826_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='belongingsdonatorinfo',
            name='is_submitted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
